analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.471632
  lightness: 0.102016
  rhythmicContrast: 0.033435
  saturation: 0.068962
cta: {}
layout_spectrum: 0.382882
name: Flyte
opengraph: {}
purpose: []
typography_spectrum: 0.217342
